

SELECT B.USER_ID, B.NICKNAME, CONCAT(B.CITY," ",B.STREET_ADDRESS1," ",B.STREET_ADDRESS2),CONCAT(SUBSTR(B.TLNO,1,3),'-',SUBSTR(B.TLNO,4,4),'-',SUBSTR(B.TLNO,8,4))
FROM USED_GOODS_BOARD A INNER JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE 1=1
GROUP BY A.WRITER_ID
HAVING COUNT(A.WRITER_ID) >=3
ORDER BY B.USER_ID DESC

