# -- 코드를 입력하세요
SELECT PRODUCT_ID,PRODUCT_NAME,SUM(TOTAL_SALES) AS TOTAL_SALES
FROM(
SELECT A.PRODUCT_ID,A.PRODUCT_NAME,A.PRICE*B.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT A INNER JOIN FOOD_ORDER B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE 1=1
AND DATE_FORMAT(B.PRODUCE_DATE,'%Y-%m') = '2022-05'
) A
GROUP BY A.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC

# SELECT *
# FROM FOOD_PRODUCT A INNER JOIN FOOD_ORDER B
# ON A.PRODUCT_ID = B.PRODUCT_ID
# WHERE 1=1
# AND DATE_FORMAT(B.PRODUCE_DATE,'%Y-%m') = '2022-05'
