-- 코드를 입력하세요
SELECT DISTINCT(A.car_id)
FROM CAR_RENTAL_COMPANY_CAR A INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
WHERE 1=1
AND A.CAR_TYPE = '세단'
AND DATE_FORMAT(B.start_date, '%m') = 10 
ORDER BY CAR_ID DESC