-- 코드를 입력하세요
# SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
# FROM(
# SELECT *, MAX(PRICE) AS MAX_PRICE
# FROM FOOD_PRODUCT 
# GROUP BY CATEGORY
#     ) A
# WHERE 1=1
# AND A.CATEGORY IN ('과자','국','김치','식용유')
# ORDER BY MAX_PRICE DESC

# SELECT PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE 1=1
# AND PRICE = (SELECT MAX(PRICE) AS MAX_PRICE
# FROM FOOD_PRODUCT 
# GROUP BY CATEGORY)

SELECT CATEGORY,MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT 
WHERE 1=1
AND CATEGORY IN ('과자','국','김치','식용유')
AND PRICE IN (SELECT MAX(PRICE)
             FROM FOOD_PRODUCT
             GROUP BY CATEGORY)
GROUP BY PRODUCT_NAME,CATEGORY
ORDER BY MAX_PRICE DESC